# ==========================================
# GENERAL SETTINGS
# ==========================================

# Terminal & Colors
# set -g default-terminal "screen-256color"
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Indexing
set -g base-index 1          # Start windows numbering from index 1
setw -g pane-base-index 1     # Start panes numbering from index 1

# Performance
set -sg escape-time 1        # Shorten command delay

# Mouse Support
set -g mouse on


# ==========================================
# KEYBINDINGS
# ==========================================

# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes using / and . (opens in same path)
bind / split-window -h -c "#{pane_current_path}"
unbind-key .
bind-key . split-window -v -c "#{pane_current_path}"

# Mouse toggle
bind-key m set-option -g mouse \; display-message "Mouse is now #{?mouse,on,off}"

# Reload config file
bind r source-file ~/.tmux.conf \; display-message 'Config: RELOADED'

# (Disabled) Resize panes
# bind-key -r j resize-pane -D 5
# bind-key -r k resize-pane -U 5
# bind-key -r h resize-pane -L 5
# bind-key -r l resize-pane -R 5


# ==========================================
# VISUAL STYLES (Colors & Panes)
# ==========================================

# Pane color outline
set -g pane-border-style fg="#222222"
set -g pane-active-border-style fg=colour214

# Pane Titles (Top)
set-option -g pane-border-status top
set-option -g pane-border-format " #{pane_index} ~ #{pane_current_command} "

# Clock color (C-a + t)
set-option -g clock-mode-colour "#ffd700"
set-option -g clock-mode-style 12


# ==========================================
# STATUS LINE
# ==========================================

set-option -g status on
set -g status-interval 3
set -g status-justify centre

# Status Colors
set-option -g status-bg colour235 # base02
set-option -g status-fg yellow    # yellow

# Nested Tmux Indicator
wg_is_keys_off="#[fg=#ff0000]#([ $(tmux show-option -qv key-table) = 'off' ] && echo '⛔')#[default]"

# --- Status Left (Hostname, IP, Network Info)
set -g status-left-length 80
set -g status-left " #[fg=yellow]#h #[fg=#737373]#(PATH=\$PATH:/sbin:/usr/sbin:/bin:/usr/bin; if command -v ip >/dev/null 2>&1; then ip -4 addr show; else ifconfig; fi | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1 | grep -v '127.0.0.1' | xargs echo) #[fg=white]﹅ #[fg=#DBDBDB]#(IP=\$(dig -4 +short myip.opendns.com @resolver1.opendns.com +time=1 +tries=1); echo \${IP:-OFFLINE}) #[fg=#FF6685]$wg_is_keys_off "

# --- Status Middle (Windows)
set-option -g window-status-current-format '#[fg=black,bg=yellow] #{window_index} '
set-option -g window-status-format '#{window_index} '

# --- Status Right (Date & Time)
set -g status-right-length 60
set -g status-right "#[fg=#ffd700]%a %Y-%m-%d #[fg=green]%l:%M %p "
